blank_issues_enabled: true
contact_links:
  - name: Problemen met vertalingen
    url: https://github.com/agroqirax/TimberbornNederlandsTaalpakket/issues/new?template=translations-issue.yml
    about: "Meld een verkeerde vertaling"
  - name: Vertaal mijn mod niet
    url: https://github.com/agroqirax/TimberbornNederlandsTaalpakket/issues/new?template=remove-translations.yml
    about: "Verzoek om bepaalde mod niet te vertalen indienen"
  - name: Vertaal deze mod
    url: https://github.com/agroqirax/TimberbornNederlandsTaalpakket/issues/new?template=new-translations.yml
    about: "Suggereer een mod om te vertalen"
